[project]
name = "repl-nix-stocktradeanalyzer"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "ib-insync>=0.9.86",
    "plotly>=5.24.1",
    "streamlit>=1.41.1",
]
